name: hknews
description: A new Flutter application.

version: 1.2.1+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hknews_repository:
    path: packages/hknews_repository

  timeago: ^2.0.28
  url_launcher: ^5.7.10
  big_tip: ^1.1.1
  package_info: ^0.4.3+2
  flutter_email_sender: ^3.0.1
  flutter_web_browser: ^0.13.0
  flutter_markdown: ^0.5.1
  flutter_i18n: ^0.20.1
  launch_review: ^2.0.0
  row_collection: ^0.2.4
  cherry_components: ^0.0.1+4
  google_fonts: ^1.1.1
  stream_transform: ^1.2.0
  system_setting: ^0.1.3
  equatable: ^1.2.5
  bloc: ^6.1.0
  flutter_bloc: ^6.1.1
  hydrated_bloc: ^6.1.0
  formz: ^0.3.2
  flutter_slidable: ^0.5.7
  http: ^0.12.2
  shimmer: ^1.1.2
  flutter_html: ^1.1.1
  share: '>=0.6.5 <2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  flutter_native_splash: ^0.1.9

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/launcher_icon.png"
  adaptive_icon_background: "#ffffff"

flutter_native_splash:
  image: "assets/icon/splash_icon.png"
  color: "#FB4E06"

flutter:
  assets:
    - assets/flutter_i18n/
  uses-material-design: true

