name: hacker_news
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

#  cupertino_icons: ^0.1.2
  firebase: ^5.0.0
  timeago: ^2.0.25
  url_launcher: ^5.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/launcher_icon.png"


flutter:
  uses-material-design: true

