name: hacker_news
description: A new Flutter application.

version: 1.1.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

#  cupertino_icons: ^0.1.2
  firebase: ^5.0.0
  dio: ^3.0.10
  timeago: ^2.0.25
  url_launcher: ^5.4.7
  big_tip: ^1.1.1
  package_info: ^0.4.3
  flutter_email_sender: ^3.0.1
  flutter_web_browser: ^0.11.0
  flutter_markdown: ^0.4.3
  flutter_i18n: ^0.19.1
  launch_review: ^2.0.0
  provider: ^4.3.2+1
  row_collection: ^0.2.4
  cherry_components: ^0.0.1+2
  google_fonts: ^1.1.0
  shared_preferences: ^0.5.10
  stream_transform: ^1.2.0
  system_setting: ^0.1.3
  sqflite: ^1.3.1
  path_provider: ^1.6.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/launcher_icon.png"

flutter:
  assets:
    - assets/flutter_i18n/
  uses-material-design: true

