name: Flutter CI

on:  
  push:
    branches:
      - master
    tags:        
      - '*'
  pull_request:
    branches:
      - master
    
# on: push    # Default will running for every branch.
    
jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
    
    # Setup Java environment in order to build the Android app.
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    
    # Setup the flutter environment.
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable' # 'dev', 'alpha', default to: 'stable'
        flutter-version: '1.22.x' # you can also specify exact version of flutter
    
    # Print flutter enviroment
    - run: flutter --version

    # Get flutter dependencies.
    - run: flutter pub get
    
    # Check for any formatting issues in the code.
    - run: flutter format --set-exit-if-changed .
    
    # Statically analyze the Dart code for any errors.
    - run: flutter analyze .
    
    # Run widget tests for our flutter project.
    - run: flutter test

    # Create Android Signing key
    - name: Create Android signing key
      run: echo $SIGNING_KEY | base64 -d > android/app/key.jks
      env:
        SIGNING_KEY: ${{ secrets.HKNEWS_SIGNING_KEY }}
    
    # Build and signed apks.
    - run: flutter build apk --split-per-abi
      env:
        KEY_STORE_PASSWORD: ${{ secrets.HKNEWS_KEY_STORE_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.HKNEWS_KEY_PASSWORD }}
        ALIAS: ${{ secrets.HKNEWS_KEY_ALIAS }}
        KEY_PATH: key.jks
      continue-on-error: true
    
    # Upload generated apk to the artifacts.
    - uses: actions/upload-artifact@v2
      with:
        name: release-apk
        path: build/app/outputs/apk/release/

    # Build and signed appbundle.
    - run: flutter build appbundle
      env:
        KEY_STORE_PASSWORD: ${{ secrets.HKNEWS_KEY_STORE_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.HKNEWS_KEY_PASSWORD }}
        ALIAS: ${{ secrets.HKNEWS_KEY_ALIAS }}
        KEY_PATH: key.jks
    
    # Upload generated appbundle to the artifacts.
    - uses: actions/upload-artifact@v2
      with:
        name: release-appbundle
        path: build/app/outputs/bundle/release/
