name: release

on:
  workflow_run:
    workflows: ["build"]
    branches: [release]
    types: [completed]
  release:
    types: [published]

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
    - run: flutter pub get
    - name: Create google-services.json file
      run: echo $GOOGLE_SERVICES_JSON > android/app/google-services.json
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
    - name: Create Android signing key
      run: echo $SIGNING_KEY | base64 -d > android/app/key.jks
      env:
        SIGNING_KEY: ${{ secrets.HKNEWS_SIGNING_KEY }}
    - run: flutter build apk --split-per-abi
      env:
        KEY_STORE_PASSWORD: ${{ secrets.HKNEWS_KEY_STORE_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.HKNEWS_KEY_PASSWORD }}
        ALIAS: ${{ secrets.HKNEWS_KEY_ALIAS }}
        KEY_PATH: key.jks
      continue-on-error: true
    - name: Upload apks
      uses: actions/upload-artifact@v2
      with:
        name: release-apk
        path: build/app/outputs/apk/release/
    - run: flutter build appbundle
      env:
        KEY_STORE_PASSWORD: ${{ secrets.HKNEWS_KEY_STORE_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.HKNEWS_KEY_PASSWORD }}
        ALIAS: ${{ secrets.HKNEWS_KEY_ALIAS }}
        KEY_PATH: key.jks
    - name: Upload appbundle
      uses: actions/upload-artifact@v2
      with:
        name: release-appbundle
        path: build/app/outputs/bundle/release/
